app/config/urls.py
from django.contrib import admin
from django.urls import path, include

from core.erp.views.tests.views import TestView, TestClientView
from core.homepage.views import IndexView

from django.conf import settings
from django.conf.urls.static import static

from core.login.views import LoginFormView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('erp/', include('core.erp.urls')),
    path('login/', include('core.login.urls')),
    path('reports/', include('core.reports.urls')),
    path('user/', include('core.user.urls')),
    path('', LoginFormView.as_view(), name='index'),
    # path('', IndexView.as_view(), name='index'), ---homepage---sin-uso
    # path('test/', TestView.as_view(), name='test'), ---test--sin-uso
    # path('testClient/', TestClientView.as_view(), name='testClient'), ---test--sin-uso
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/core/erp/urls.py
from django.urls import path

from core.erp.views.abono.views import AbonoListView, AbonoCreateView, AbonoUpdateView, AbonoDeleteView
from core.erp.views.category.views import CategoryCreateView, CategoryListView, CategoryUpdateView, CategoryDeleteView
from core.erp.views.clientPending.views import ClientPendingListView, ClientPendingDeleteView, ClientPendingListPdf, \
    ClientPendingDeleteAllView
from core.erp.views.dashboard.views import DashboardView
from core.erp.views.equipRemove.views import EquipRemoveListView, EquipRemovePdfView
from core.erp.views.equipSuspend.views import EquipSuspendListView
from core.erp.views.invoice.views import InvoiceListView, InvoiceCreateView, InvoiceDeleteView, InvoicePdfView
from core.erp.views.jobTecnic.views import JobTecnicCreateView, JobTecnicListView, JobTecnicUpdateView, \
    JobTecnicDeleteView, JobTecnicMonthlyPlanning
from core.erp.views.pay.views import PayListView, PayCreateView, PayUpdateView, PayDeleteView, PayPrintPdfView, \
    PayCreateViewTest
from core.erp.views.product.views import ProductListView, ProductCreateView, ProductUpdateView, ProductDeleteView
from core.erp.views.client.views import *
from core.erp.views.sale.views import SaleCreateView, SaleListView, SaleDeleteView, SaleInvoicePdfView
from core.erp.views.tecnic.views import TecnicListView, TecnicCreateView, TecnicUpdateView, TecnicDeleteView
from core.erp.views.tests.views import TestView
from core.erp.views.zone.views import ZoneListView, ZoneCreateView, ZoneDeleteView, ZoneUpdateView, ZoneRoutePdfView, \
    ZoneOrderView

app_name = 'erp'

urlpatterns = [
    # home
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    # client
    path('client/list/', ClientListView.as_view(), name='client_list'),
    path('client/add/', ClientCreateView.as_view(), name='client_create'),
    path('client/update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('client/delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    path('client/saldos/', ClientSaldoView.as_view(), name='client_saldos'),
    path('client/saldos/pdf/<int:ti>/<int:zi>/<str:t_pay>/<str:d_start>/<str:d_end>/', ClientSaldoPdf.as_view(),
         name='client_saldos_pdf'),
    # abono
    path('abono/list/', AbonoListView.as_view(), name='abono_list'),
    path('abono/add/', AbonoCreateView.as_view(), name='abono_create'),
    path('abono/update/<int:pk>/', AbonoUpdateView.as_view(), name='abono_update'),
    path('abono/delete/<int:pk>/', AbonoDeleteView.as_view(), name='abono_delete'),
    # tecnic
    path('tecnic/list/', TecnicListView.as_view(), name='tecnic_list'),
    path('tecnic/add/', TecnicCreateView.as_view(), name='tecnic_create'),
    path('tecnic/update/<int:pk>/', TecnicUpdateView.as_view(), name='tecnic_update'),
    path('tecnic/delete/<int:pk>/', TecnicDeleteView.as_view(), name='tecnic_delete'),
    # category
    path('category/list/', CategoryListView.as_view(), name='category_list'),
    path('category/add/', CategoryCreateView.as_view(), name='category_create'),
    path('category/update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),
    # product
    path('product/list/', ProductListView.as_view(), name='product_list'),
    path('product/add/', ProductCreateView.as_view(), name='product_create'),
    path('product/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    # sale
    path('sale/list/', SaleListView.as_view(), name='sale_list'),
    path('sale/add/', SaleCreateView.as_view(), name='sale_create'),
    path('sale/delete/<int:pk>/', SaleDeleteView.as_view(), name='sale_delete'),
    path('sale/invoice/pdf/<int:pk>/', SaleInvoicePdfView.as_view(), name='sale_invoice_pdf'),
    # zone
    path('zone/list/', ZoneListView.as_view(), name='zone_list'),
    path('zone/add/', ZoneCreateView.as_view(), name='zone_create'),
    path('zone/update/<int:pk>/', ZoneUpdateView.as_view(), name='zone_update'),
    path('zone/delete/<int:pk>/', ZoneDeleteView.as_view(), name='zone_delete'),
    path('zone/route/pdf/<int:pk>/', ZoneRoutePdfView.as_view(), name='zone_route'),
    path('zone/orderzone/<int:pk>/', ZoneOrderView.as_view(), name='zone_order'),
    # pay
    path('pay/list/', PayListView.as_view(), name='pay_list'),
    path('pay/add/', PayCreateView.as_view(), name='pay_create'),
    path('pay/add/test/', PayCreateViewTest.as_view(), name='pay_create_test'),
    path('pay/update/<int:pk>/', PayUpdateView.as_view(), name='pay_update'),
    path('pay/delete/<int:pk>/', PayDeleteView.as_view(), name='pay_delete'),
    path('pay/print/pdf/<int:pk>/', PayPrintPdfView.as_view(), name='sale_invoice_pdf'),
    # invoice
    path('invoice/list/', InvoiceListView.as_view(), name='invoice_list'),
    path('invoice/add/', InvoiceCreateView.as_view(), name='invoice_create'),
    path('invoice/delete/<int:pk>/', InvoiceDeleteView.as_view(), name='invoice_delete'),
    path('invoice/pdf/<int:pk>/', InvoicePdfView.as_view(), name='invoice_pdf'),
    # jobTecnic
    path('jobTecnic/list/', JobTecnicListView.as_view(), name='jobTecnic_list'),
    path('jobTecnic/add/', JobTecnicCreateView.as_view(), name='jobTecnic_create'),
    path('jobTecnic/update/<int:pk>/', JobTecnicUpdateView.as_view(), name='jobTecnic_update'),
    path('jobTecnic/delete/<int:pk>/', JobTecnicDeleteView.as_view(), name='jobTecnic_delete'),
    path('jobTecnic/month-planning/', JobTecnicMonthlyPlanning.as_view(), name='jobTecnicMonthPlanning_list'),
    # clientPending
    path('clientPending/list/', ClientPendingListView.as_view(), name='clientPending_list'),
    path('clientPending/delete/<int:pk>/', ClientPendingDeleteView.as_view(), name='clientPending_delete'),
    path('clientPending/delete/all/', ClientPendingDeleteAllView.as_view(), name='clientPending_delete_all'),
    path('clientPending/list/pdf/<int:ti>/', ClientPendingListPdf.as_view(), name='clientPending_list_pdf'),
    # equipRemove
    path('equipRemove/list/', EquipRemoveListView.as_view(), name='equipRemove_list'),
    path('equipRemove/pdf/<int:pk>/', EquipRemovePdfView.as_view(), name='equipRemove_pdf'),
    # equipSuspend
    path('equipSuspend/list/', EquipSuspendListView.as_view(), name='equipSuspend_list'),
    # test
    path('test/', TestView.as_view(), name='test_view'),
]

app/core/erp/views/dashboard/views.py
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum, Count
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView

from core.erp.models import Invoice, Client, Services
from core.erp.views.client.views import get_client_abono


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard.html'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        request.user.get_group_session()
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'get_graph_sales_year_month':
                year = request.POST['year']
                # se va a enviar los datos en un array para trabajar con datatables y ajax

                data = {
                    'name': 'Total de Facturación',
                    'showInLegend': False,
                    'colorByPoint': True,
                    'data': self.get_graph_sales_year_month(year)
                }
            elif action == 'get_data_dashboard_resume':
                # excluir tecnicos no deberia estar ( si el listado de clientes activos fueran los correctos )
                clients = Client.objects.filter(active=True, enable=True).exclude(tecnic_id=1).exclude(tecnic_id=5).count()
                equips = Services.objects.filter(cli__enable=True, cli__active=True).exclude(cli__tecnic_id=1).aggregate(total=Sum('cant_odo'))
                fact = Client.objects.filter(active=True, enable=True).exclude(tecnic_id=1).exclude(tecnic_id=5).values_list('id', flat=True)
                total_fact = 0
                for i in list(fact):
                    total_fact += get_client_abono(i)

                data = {
                    'cant_equipos': equips['total'],
                    'cant_clientes': clients,
                    'total_facturacion': '$ {:,}'.format(total_fact).replace(',','.'),
                }
            else:
                data['error'] = 'Ha ocurrido un error'
        except Exception as e:
            data['error'] = str(e)
        # safe=False se utiliza cuando se quiere serializar objetos que no son del diccionario
        return JsonResponse(data, safe=False)

    def get_graph_sales_year_month(self, year):
        # year = datetime.now().year
        # year = int(year)
        data = []
        try:
            for m in range(1, 13):
                total = Invoice.objects.filter(date_joined__year=year, date_joined__month=m).aggregate(
                    r=Sum('total', default=0)).get('r')
                if total is not None:
                    data.append(float(total))
                else:
                    data.append(0.0)
        except:
            pass
        return data

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['panel'] = 'Panel de Administrador'
        context['entity'] = 'Dashboard'
        context['year'] = datetime.now().year
        return context

app/templates/dashboard.html
{% extends 'layout.html' %}
{% load static %}
{% block head %}
    <script src="{% static 'lib/Highcharts-10.1.0/code/highcharts.js' %}"></script>
    <script src="{% static 'lib/Highcharts-10.1.0/code/modules/exporting.js' %}"></script>
    <script src="{% static 'lib/Highcharts-10.1.0/code/modules/export-data.js' %}"></script>
    <script src="{% static 'lib/Highcharts-10.1.0/code/modules/accessibility.js' %}"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/css/dashboard.css' %}">

{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class='buttons' id="buttons">
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div id="container"></div>
            </div>
        </div>
        <br>
        <br>
        <br>
        <div class="row">
            <div class="col-lg-4 col-md-6 col-sm-6 col-12">
                <div class="small-box bg-info">
                    <div class="inner">
                        <h3 id="cant_equipos">--</h3>
                        <p>Equipos</p>
                    </div>
                    <div class="icon">
                        <i class="fas fa-briefcase"></i>
                    </div>
                    <a href="#" class="small-box-footer">
                        More info <i class="fas fa-arrow-circle-right"></i>
                    </a>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-6 col-12">
                <div class="small-box bg-gradient-success">
                    <div class="inner">
                        <h3 id="cant_clientes">--</h3>
                        <p>Clientes</p>
                    </div>
                    <div class="icon">
                        <i class="fas fa-users"></i>
                    </div>
                    <a href="#" class="small-box-footer">
                        More info <i class="fas fa-arrow-circle-right"></i>
                    </a>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-6 col-12">
                <div class="small-box bg-gradient-secondary">
                    <div class="inner">
                        <h3 id="total_facturacion">$ --</h3>
                        <p>Facturación Mensual</p>
                    </div>
                    <div class="icon">
                        <i class="fas fa-hand-holding-usd"></i>
                    </div>
                    <a href="#" class="small-box-footer">
                        More info <i class="fas fa-arrow-circle-right"></i>
                    </a>
                </div>
            </div>
        </div>
        <br>
    </div>


    <script src="{% static 'dashboard/js/dashboard.js' %}"></script>
{% endblock %}

app/templates/delete.html
{% extends 'layout.html' %}

{#Este bloque contiene el formulario dentro del body#}
{% block content %}
    <form method="post" action="erp">
        <div class="card card-default">
            <div class="card-header">
                <h3 class="card-title">
                    <i class="fas fa-trash"></i>
                    {{ title }}
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {#            variable action recibida del context data para luego enviarla a a traves del metodo post#}
                {#            necesario para utilizar la tecnologia ajax#}
                <input type="hidden" name="action" value="{{ action }}">
                {#            itera los campos del formulario para luego personalizar los campos#}
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h5><i class="icon fas fa-ban"></i> Ha ocurrido un error al crear un cliente</h5>
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
            </div>
            <div class="alert alert-danger alert-dismissible">
                <h5><i class="icon fas fa-ban"></i> Notificación!</h5>
                {% if object.id %}
                ¿Estas seguro de eliminar el registro Nro: {{ object.id }}?
                {% else %}
                    ¿Estas seguro de eliminar todos los registros?
                {% endif %}
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary btnTest">
                    <i class="fas fa-save"></i> Si, Aceptar
                </button>
                <a href="{{ list_url }}" class="btn btn-info btnTest">
                    <i class="fas fa-times"></i> Cancelar
                </a>
            </div>
        </div>
    </form>

    <script>
        {#codigo ajax para eliminar un objeto de la base de datos#}
        $('form').on('submit', function (e) {
            e.preventDefault();
            {#ver como funciona el FormData#}
            var parameters = new FormData(this);
            console.log(parameters);
            submit_with_ajax(window.location.pathname, 'Notificación', '¿Estas seguro de eliminar el siguiente elemento?', parameters, function () {
                Swal.fire({
                    title: 'Alerta',
                    text: 'Registro eliminado correctamente',
                    icon: 'success',
                    timer: 2500,
                    onClose: () => {
                        location.href = '{{ list_url }}';
                    }
                })
            });
        });
    </script>


{% endblock %}

app/templates/footer.html
<!-- Main Footer -->
<footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
        Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2014-2019 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
</footer>

app/templates/form.html
{% extends 'layout.html' %}
{% load widget_tweaks %}

{% block head%}
{% endblock %}

{% block content %}
    <form method="post" action="" enctype="multipart/form-data" name="form">
        <div class="card card-default">
            <div class="card-header">
                <h3 class="card-title">
                    {% if action == 'add' %}
                        <i class="fas fa-plus-circle"></i>
                    {% else %}
                        <i class="fas fa-edit"></i>
                    {% endif %}
                    {{ title }}
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {#            variable action recibida del context data para luego enviarla a a traves del metodo post#}
                {#            necesario para utilizar la tecnologia ajax#}
                <input type="hidden" name="action" value="{{ action }}">
                {#            itera los campos del formulario para luego personalizar los campos#}
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h5><i class="icon fas fa-ban"></i> Ha ocurrido un error al crear un cliente</h5>
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}

                {% block field_enable %}

                {% endblock %}
                {% for field in form.visible_fields %}
                    {% if field.label != 'Habilitado' and field.label != 'Activado' %}
                        <div class="form-group">
                            <label for="email"> {{ field.label }}:</label>
                            {{ field }}
                        </div>
                    {% endif %}
                {% endfor %}
                {% block field_edit %}

                {% endblock %}

            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i>
                    Guardar {{ entity }}
                </button>
                <a href="{{ list_url }}" class="btn btn-danger "><i class="fas fa-times"></i>
                    Cancelar
                </a>
            </div>
        </div>
    </form>

    <script>
        {#codigo para la notificacion sweetAlert#}
        {% if form.errors %}
            var errors = '';
            {% for field in form %}
                {% for error in field.errors %}
                    errors += '{{ error }}\n';
                {% endfor %}
            {% endfor %}
            {#coontrolando errores provenientes del forms que no pertenecen al componente#}
            {% for error in form.non_field_errors %}
                errors += '{{ error }}\n';
            {% endfor %}
            Swal.fire({
                icon: 'error',
                title: 'Ha ocurrido un error',
                text: errors,
                confirmButtonText: 'Reintentar'
            });
        {% endif %}

        {#codigo ajax para acceder al evento del boton submit (guardar registro) del formulario form#}
        $('form').on('submit', function (e) {
            e.preventDefault();
            var parameters = new FormData(this);
            submit_with_ajax(window.location.pathname, 'Notificación', '¿Estas seguro de actualizar el siguiente elemento?', parameters, function () {
                location.href = '{{ list_url }}';
            });
        });

    </script>

{% endblock %}

app/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{{ title }}</title>
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.0.4/plugins/font-awesome-5.11.1/css/all.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.0.4/css/adminlte.min.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <!-- jQuery -->
    <script src="{% static 'lib/adminlte-3.0.4/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'lib/adminlte-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'lib/adminlte-3.0.4/js/adminlte.min.js' %}"></script>
    <!-- Sweetalert2 -->
    <script src="{% static 'lib/sweetalert2-9.10.0/sweetalert2.all.min.js' %}"></script>
    <!-- Jquery Confirm -->
    <link rel="stylesheet" href="{% static 'lib/jquery-confirm-v3.3.4/jquery-confirm.min.css' %}">
    <script src="{% static 'lib/jquery-confirm-v3.3.4/jquery-confirm.min.js' %}"></script>
    <!-- My css -->
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
    <!-- Funciones creadas por mi -->
    <script src="{% static 'js/functions.js' %}"></script>
    <!-- Block Head -->
    {% block head %}

    {% endblock %}
</head>

{% block body %}

{% endblock %}
</html>

app/templates/layout.html
{% extends 'vtc/body.html' %}

app/templates/list.html
{% extends 'layout.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'lib/datatables-1.10.20/css/dataTables.bootstrap4.min.css' %}"/>
    <link rel="stylesheet"
          href="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/css/responsive.bootstrap4.min.css' %}"/>
    <script src="{% static 'lib/datatables-1.10.20/js/jquery.dataTables.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/responsive.bootstrap4.min.js' %}"></script>

    {% block head_list %}

    {% endblock %}
{% endblock %}

{% block content %}
    <div class="card card-default">
        <div class="card-header">
            <h3 class="card-title">
                <i class="fas fa-search"></i>
                {{ title }} | {{ date_now }}
            </h3>
        </div>
        {% block filterDataTable %}

        {% endblock %}
        {% block enableClients %}

        {% endblock %}
        <div class="card-body">

            <table class="table table-striped" id="data">
                <thead class="thead-dark">
                {% block columns %}

                {% endblock %}

                </thead>
                <tbody>
                {% block rows %}

                {% endblock %}
                </tbody>
            </table>
        </div>
        <div class="card-footer" id="card-footer">
            <a href="{{ create_url }}" class="btn btn-primary btnTest"><i class="fas fa-address-book"></i>
                Nuevo {{ entity }}
            </a>
            <a href="{{ list_url }}" class="btn btn-success"><i class="fas fa-sync"></i>
                Actualizar
            </a>
        </div>
    </div>
{% endblock %}

{#bloque para cargar los datos en el datatable#}
{% block javascript %}
    <script type="application/javascript">
        $(function () {
            $('#data').DataTable({
                responsive: true,
                autoWidth: false
            });
            $('.btnTest').on('click', function () {
                $.ajax({
                    url: '{% url 'erp:client_list' %}',
                    type: 'POST',
                    data: {id: 1},
                    DataType: 'json'
                }).done(function (data) {
                    console.log(data);
                }).fail(function (jqXHR, textStatus, errorThrown) {
                    alert(textStatus + ': ' + errorThrown)
                });
            });
        });
    </script>
{% endblock %}